---
application:
  name: "All in One Bot"
  project: "All in One Bot"
  organization: "Kavi Bots"
databases:
- type: "MYSQL"
  name: "renamebotsj"
  version: "8.0"
routers:
- name: "main-filerenamebot"
  routes:
  - application_name: "filerenamebot"
    paths:
    - "/*"
